-- 023_import_clientes_planilha.sql
-- Importa/atualiza grupo_servico + tem_orquidea de 120 clientes vindos da
-- planilha clientes-servicos.xlsx (comparação case-insensitive por nome).
--
-- Uso:
--   1. Cole tudo isso no Supabase SQL Editor e execute.
--   2. Ao final aparece uma lista das empresas do CRM que NÃO estão
--      na planilha — copie e me mande pra revisarmos juntas o que falta.

BEGIN;

CREATE TEMP TABLE IF NOT EXISTS _planilha (
  nome_empresa   TEXT PRIMARY KEY,
  grupo_servico  TEXT NOT NULL,
  tem_orquidea   BOOLEAN NOT NULL,
  obs            TEXT
) ON COMMIT DROP;

INSERT INTO _planilha (nome_empresa, grupo_servico, tem_orquidea, obs) VALUES
  ('SPX', 'Locação', TRUE, NULL),
  ('SUPERA', 'Manutenção com troca', FALSE, NULL),
  ('ARGUS', 'Manutenção com troca', FALSE, NULL),
  ('ARCADIS', 'Manutenção com troca', TRUE, NULL),
  ('APDATA', 'Locação', TRUE, NULL),
  ('CHS', 'Manutenção com troca', TRUE, NULL),
  ('CLINICA MATHEUS', 'Somente orquídea', TRUE, NULL),
  ('INGERSOLL', 'Locação', TRUE, NULL),
  ('FERRERO', 'Manutenção com troca', TRUE, NULL),
  ('TRACK AND FIELD LOJA', 'Manutenção com troca', FALSE, NULL),
  ('ACCESSTAGE', 'Manutenção com troca', TRUE, NULL),
  ('OKTA', 'Manutenção com troca', TRUE, NULL),
  ('FORTINET', 'Manutenção com troca', TRUE, NULL),
  ('RANDSTAD', 'Manutenção com troca', TRUE, NULL),
  ('RM ADV', 'Locação', TRUE, NULL),
  ('BOA VISTA INV', 'Locação', TRUE, NULL),
  ('MITSUI', 'Locação', FALSE, NULL),
  ('PACAEMBU', 'Locação', FALSE, NULL),
  ('OLIVEIRA TRUST', 'Manutenção com troca', TRUE, NULL),
  ('ESSOR', 'Manutenção com troca', FALSE, NULL),
  ('COLLIERS', 'Manutenção com troca', TRUE, NULL),
  ('PTC', 'Locação', TRUE, NULL),
  ('HANDRED', 'Locação', FALSE, NULL),
  ('FRESENIUS', 'Manutenção com troca', TRUE, NULL),
  ('FTI', 'Locação', TRUE, NULL),
  ('LIVE HIGIENOPOLIS', 'Manutenção com troca', FALSE, NULL),
  ('live butanta', 'Manutenção com troca', FALSE, NULL),
  ('FNS', 'Manutenção com troca', FALSE, NULL),
  ('CAIXABANK', 'Locação', TRUE, NULL),
  ('BDB', 'Manutenção com troca', TRUE, NULL),
  ('KOVR', 'Manutenção com troca', TRUE, NULL),
  ('EUROP', 'Locação', TRUE, NULL),
  ('ELECTROLUX', 'Locação', FALSE, NULL),
  ('MILLS', 'Locação', TRUE, NULL),
  ('GHT4', 'Locação', TRUE, NULL),
  ('SYSMEX NAÇÕES', 'Manutenção com troca', TRUE, NULL),
  ('KOBRE & KIM', 'Manutenção com troca', TRUE, NULL),
  ('MJC', 'Locação', FALSE, NULL),
  ('ALTBANK', 'Locação', FALSE, NULL),
  ('FLORA', 'Manutenção com troca', FALSE, NULL),
  ('TRACK AND FIELD ESCRITORIO', 'Manutenção com troca', TRUE, NULL),
  ('AUSTER OPPORTUNITY', 'Locação', TRUE, NULL),
  ('SME', 'Manutenção', FALSE, NULL),
  ('ALLIED', 'Manutenção com troca', FALSE, NULL),
  ('EXPANSCIENCE', 'Manutenção com troca', FALSE, NULL),
  ('F INICIATIVAS', 'Locação', TRUE, NULL),
  ('PULLSE', 'Manutenção', FALSE, NULL),
  ('SOLENIS', 'Manutenção com troca', FALSE, NULL),
  ('DIPROMED', 'Manutenção com troca', FALSE, NULL),
  ('ABBOTT', 'Manutenção com troca', FALSE, NULL),
  ('INDIGO', 'Manutenção com troca', FALSE, NULL),
  ('LACTALIS', 'Manutenção com troca', FALSE, NULL),
  ('LIVE OSCAR FREIRE', 'Manutenção com troca', FALSE, NULL),
  ('23S CAPITAL', 'Manutenção com troca', TRUE, NULL),
  ('FORMITEX', 'Manutenção com troca', FALSE, NULL),
  ('EACE', 'Manutenção com troca', TRUE, NULL),
  ('VARANDA ANDRE OKTA', 'Manutenção', FALSE, NULL),
  ('ECOLAB', 'Manutenção com troca', FALSE, NULL),
  ('TERA CAPITAL', 'Manutenção com troca', TRUE, NULL),
  ('NAU CAPITAL', 'Manutenção com troca', TRUE, NULL),
  ('ARQIA', 'Locação', FALSE, NULL),
  ('HID', 'Manutenção com troca', TRUE, NULL),
  ('ELEKTA', 'Manutenção com troca', FALSE, NULL),
  ('MATRIBANK', 'Manutenção', FALSE, NULL),
  ('RESMED', 'Manutenção com troca', FALSE, NULL),
  ('SINDONA', 'Manutenção com troca', FALSE, NULL),
  ('PEGAS ADV', 'Locação', FALSE, NULL),
  ('GERSON & GREY', 'Manutenção com troca', FALSE, NULL),
  ('LBR', 'Manutenção com troca', FALSE, NULL),
  ('GRIMBERG', 'Manutenção', FALSE, NULL),
  ('ABIEC', 'Manutenção', FALSE, NULL),
  ('TITO', 'Manutenção com troca', FALSE, NULL),
  ('EAD', 'Manutenção com troca', FALSE, NULL),
  ('UL', 'Manutenção com troca', FALSE, NULL),
  ('COND. PAULISTA', 'Locação', TRUE, NULL),
  ('KINGSTON', 'Manutenção com troca', FALSE, NULL),
  ('RHEEM', 'Manutenção com troca', FALSE, NULL),
  ('SERVICE', 'Manutenção com troca', FALSE, NULL),
  ('SOMFY', 'Manutenção com troca', FALSE, NULL),
  ('CORELAW', 'Manutenção', TRUE, NULL),
  ('LEXIS NEXIS', 'Manutenção com troca', FALSE, NULL),
  ('ALTONA', 'Manutenção com troca', FALSE, NULL),
  ('CHIAROTTINO', 'Manutenção', FALSE, NULL),
  ('ALLEN OVERY', 'Manutenção com troca', FALSE, NULL),
  ('JUSTEN', 'Somente orquídea', TRUE, NULL),
  ('BR COMPANY', 'Manutenção com troca', FALSE, NULL),
  ('CBL', 'Manutenção com troca', FALSE, NULL),
  ('MED SYSTEMS', 'Somente orquídea', TRUE, NULL),
  ('LIGGA', 'Manutenção com troca', FALSE, NULL),
  ('ALIANZA', 'Manutenção com troca', FALSE, NULL),
  ('FREC', 'Manutenção', FALSE, NULL),
  ('MANEIRA ADV', 'Manutenção', FALSE, NULL),
  ('BOW-E', 'Manutenção com troca', FALSE, NULL),
  ('AFFARI', 'Somente orquídea', TRUE, NULL),
  ('EVEO', 'Manutenção', FALSE, NULL),
  ('MEDCORP', 'Manutenção', FALSE, NULL),
  ('DATORA FARIA LIMA', 'Locação', TRUE, NULL),
  ('DATORA JK', 'Locação', FALSE, NULL),
  ('THOMSON', 'Locação', TRUE, NULL),
  ('BETANO', 'Manutenção com troca', FALSE, NULL),
  ('DESK MANAGER', 'Manutenção', FALSE, NULL),
  ('CLINICA PINHEIROS', 'Manutenção', FALSE, NULL),
  ('BOLT', 'Manutenção com troca', TRUE, NULL),
  ('MONDAY', 'Manutenção com troca', FALSE, NULL),
  ('FORT GESTAO', 'Manutenção', FALSE, NULL),
  ('AMARIS', 'Manutenção', FALSE, NULL),
  ('BRADESCO', 'Manutenção', FALSE, NULL),
  ('CARLAW', 'Grupo 4 - Flores', FALSE, NULL),
  ('OLX', 'Manutenção com troca', TRUE, NULL),
  ('EMBRAER', 'Manutenção com troca', FALSE, NULL),
  ('RGSH', 'Manutenção', FALSE, NULL),
  ('CCLA', 'Manutenção', FALSE, NULL),
  ('NORDIKA', 'Manutenção com troca', TRUE, 'não pode ser roxa'),
  ('STOCK', 'Manutenção com troca', FALSE, NULL),
  ('IVI', 'Manutenção com troca', FALSE, NULL),
  ('HEIMR', 'Manutenção com troca', FALSE, NULL),
  ('NEOSERVICE', 'Manutenção', FALSE, NULL),
  ('MAPA CAPITAL', 'Manutenção', FALSE, NULL),
  ('PL ADV', 'Manutenção', FALSE, NULL),
  ('CASA FRANCIS', 'Manutenção', FALSE, NULL);

-- 1. Atualiza os clientes que já existem no CRM (match case-insensitive)
UPDATE public.clientes c
   SET grupo_servico        = p.grupo_servico,
       tem_orquidea         = p.tem_orquidea,
       observacoes_internas = CASE
         WHEN p.obs IS NULL THEN c.observacoes_internas
         WHEN c.observacoes_internas IS NULL OR c.observacoes_internas = ''
           THEN p.obs
         WHEN POSITION(p.obs IN c.observacoes_internas) > 0
           THEN c.observacoes_internas
         ELSE c.observacoes_internas || E'
' || p.obs
       END
  FROM _planilha p
 WHERE UPPER(TRIM(c.nome_empresa)) = UPPER(TRIM(p.nome_empresa));

-- 2. Insere os que NÃO existem no CRM
INSERT INTO public.clientes (
  nome_empresa, grupo_servico, tem_orquidea, observacoes_internas, ativo, lat, lng
)
SELECT p.nome_empresa, p.grupo_servico, p.tem_orquidea, p.obs, TRUE, 0, 0
  FROM _planilha p
 WHERE NOT EXISTS (
   SELECT 1 FROM public.clientes c
    WHERE UPPER(TRIM(c.nome_empresa)) = UPPER(TRIM(p.nome_empresa))
 );

COMMIT;

-- 3. Lista os clientes DO CRM que NÃO aparecem na planilha (pra você
--    conferir o que ficou de fora). Rode isso separado depois do commit.
SELECT c.nome_empresa, c.grupo_servico, c.tem_orquidea, c.ativo
  FROM public.clientes c
 WHERE NOT EXISTS (
   SELECT 1 FROM (
     VALUES
     ('SPX'),
     ('SUPERA'),
     ('ARGUS'),
     ('ARCADIS'),
     ('APDATA'),
     ('CHS'),
     ('CLINICA MATHEUS'),
     ('INGERSOLL'),
     ('FERRERO'),
     ('TRACK AND FIELD LOJA'),
     ('ACCESSTAGE'),
     ('OKTA'),
     ('FORTINET'),
     ('RANDSTAD'),
     ('RM ADV'),
     ('BOA VISTA INV'),
     ('MITSUI'),
     ('PACAEMBU'),
     ('OLIVEIRA TRUST'),
     ('ESSOR'),
     ('COLLIERS'),
     ('PTC'),
     ('HANDRED'),
     ('FRESENIUS'),
     ('FTI'),
     ('LIVE HIGIENOPOLIS'),
     ('live butanta'),
     ('FNS'),
     ('CAIXABANK'),
     ('BDB'),
     ('KOVR'),
     ('EUROP'),
     ('ELECTROLUX'),
     ('MILLS'),
     ('GHT4'),
     ('SYSMEX NAÇÕES'),
     ('KOBRE & KIM'),
     ('MJC'),
     ('ALTBANK'),
     ('FLORA'),
     ('TRACK AND FIELD ESCRITORIO'),
     ('AUSTER OPPORTUNITY'),
     ('SME'),
     ('ALLIED'),
     ('EXPANSCIENCE'),
     ('F INICIATIVAS'),
     ('PULLSE'),
     ('SOLENIS'),
     ('DIPROMED'),
     ('ABBOTT'),
     ('INDIGO'),
     ('LACTALIS'),
     ('LIVE OSCAR FREIRE'),
     ('23S CAPITAL'),
     ('FORMITEX'),
     ('EACE'),
     ('VARANDA ANDRE OKTA'),
     ('ECOLAB'),
     ('TERA CAPITAL'),
     ('NAU CAPITAL'),
     ('ARQIA'),
     ('HID'),
     ('ELEKTA'),
     ('MATRIBANK'),
     ('RESMED'),
     ('SINDONA'),
     ('PEGAS ADV'),
     ('GERSON & GREY'),
     ('LBR'),
     ('GRIMBERG'),
     ('ABIEC'),
     ('TITO'),
     ('EAD'),
     ('UL'),
     ('COND. PAULISTA'),
     ('KINGSTON'),
     ('RHEEM'),
     ('SERVICE'),
     ('SOMFY'),
     ('CORELAW'),
     ('LEXIS NEXIS'),
     ('ALTONA'),
     ('CHIAROTTINO'),
     ('ALLEN OVERY'),
     ('JUSTEN'),
     ('BR COMPANY'),
     ('CBL'),
     ('MED SYSTEMS'),
     ('LIGGA'),
     ('ALIANZA'),
     ('FREC'),
     ('MANEIRA ADV'),
     ('BOW-E'),
     ('AFFARI'),
     ('EVEO'),
     ('MEDCORP'),
     ('DATORA FARIA LIMA'),
     ('DATORA JK'),
     ('THOMSON'),
     ('BETANO'),
     ('DESK MANAGER'),
     ('CLINICA PINHEIROS'),
     ('BOLT'),
     ('MONDAY'),
     ('FORT GESTAO'),
     ('AMARIS'),
     ('BRADESCO'),
     ('CARLAW'),
     ('OLX'),
     ('EMBRAER'),
     ('RGSH'),
     ('CCLA'),
     ('NORDIKA'),
     ('STOCK'),
     ('IVI'),
     ('HEIMR'),
     ('NEOSERVICE'),
     ('MAPA CAPITAL'),
     ('PL ADV'),
     ('CASA FRANCIS')
   ) AS p(nome_empresa)
   WHERE UPPER(TRIM(c.nome_empresa)) = UPPER(TRIM(p.nome_empresa))
 )
 ORDER BY c.nome_empresa;
